const RightActionTypes = {
	FETCH_RIGHTNNOW_START: 'FETCH_RIGHTNNOW_START',
	FETCH_RIGHTNNOW_SUCCESS: 'FETCH_RIGHTNNOW_SUCCESS',
	FETCH_RIGHTNNOW_FAILURE: 'FETCH_RIGHTNNOW_FAILURE'
};

export default RightActionTypes;