
export const SCOPE = 'JOBNORGLIST';
export const FETCH_JOBNORGELIST_START = `${SCOPE}/FETCH_JOBNORGELIST_START`;
export const FETCH_JOBNORGELIST_SUCCESS = `${SCOPE}/FETCH_JOBNORGELIST_SUCCESS`;
export const FETCH_JOBNORGELIST_ERROR = `${SCOPE}/FETCH_JOBNORGELIST_ERROR`;

