
export const SCOPE = 'JOBNORGE';
export const FETCH_JOBNORGE_START = `${SCOPE}/FETCH_JOBNORGE_START`;
export const FETCH_JOBNORGE_SUCCESS = `${SCOPE}/FETCH_JOBNORGE_SUCCESS`;
export const FETCH_JOBNORGE_ERROR = `${SCOPE}/FETCH_JOBNORGE_ERROR`;

