const FourCardActionTypes = {
	FETCH_FOURCARD_START: 'FETCH_FOURCARD_START',
	FETCH_FOURCARD_SUCCESS: 'FETCH_FOURCARD_SUCCESS',
	FETCH_FOURCARD_FAILURE: 'FETCH_FOURCARD_FAILURE'
};

export default FourCardActionTypes;