
export const SCOPE = 'AIRPORTLIST';
export const FETCH_AIRPORTLIST_START = `${SCOPE}/FETCH_AIRPORTLIST_START`;
export const FETCH_AIRPORTLIST_SUCCESS = `${SCOPE}/FETCH_AIRPORTLIST_SUCCESS`;
export const FETCH_AIRPORTLIST_ERROR = `${SCOPE}/FETCH_AIRPORTLIST_ERROR`;

