 const AirportListActionTypes = {
	 FETCH_AIRPORTLIST_START: 'FETCH_AIRPORTLIST_START',
	 FETCH_AIRPORTLIST_SUCCESS: 'FETCH_AIRPORTLIST_SUCCESS',
	 FETCH_AIRPORTLIST_ERROR: 'FETCH_AIRPORTLIST_ERROR'
}



export default AirportListActionTypes;